# Generated by Django 3.2.4 on 2021-06-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0002_rename_car_make_car_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rated_car',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate_number',
            new_name='rating',
        ),
    ]
